spring:
  application:
    name: api
  profiles:
    active: dev
  datasource:
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 240000

server:
  port: 8080
  servlet:
#    context-path: /my-api
    encoding:
      charset: utf-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    display-operation-id: true
    filter: true
